[book]
authors = []
language = "zh"
multilingual = false
src = "src"

[build]
create-missing = false
build-dir = "../public/notes"

[preprocessor.katex]
renderers = ["html"]

[preprocessor.mark]
command = "mdbook-mark"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

# [preprocessor.mermaid]
# command = "mdbook-mermaid"

[output.katex]

[output.html]
git-repository-url = "https://github.com/Sciroccogti/blog-notes"
additional-css = ["mdBook-pagetoc/style.css"]
additional-js = [
#    "mdBook-pagetoc/sidebar.js",
#    "lunr.zh.js",
#    "lunr.stemmer.support.js",
#    "mdbook-mermaid/mermaid.min.js",
#    "mdbook-mermaid/mermaid-init.js",
]
no-section-label = true

[output.html.fold]
enable = true
level = 0
